server:
  port: 8089

tencentcloudapi:
  # 你的 secretId
  secretId: AKIDgv464whMqGfGrTypfUGBtNfppsvrheVF
  # 你的 secretKey
  secretKey: lPBQWPnxeZSI9zfEjaR4b5YxInWCmIlg
  # 请求官方地址 不变
  endpoint: iai.tencentcloudapi.com
  #地域 可不变
  region: ap-shanghai

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/facedb
    username: root
    password: ZJJ~2017QWQ
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: dtm_qmftzd8nnxe@163.com
    password: AJPLOHDOEOZXAALE


  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER



# spring-doc 接口文档

springdoc:
  api-docs:
    enabled: true # 是否启用接口文档
#knife4j:
#  enable: true # 是否启用 knife4j 增强,如果只是使用 knife4j 的 UI,则可以关闭



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis:
  typeAliasesPackage: com.face.bean
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true




#邮件发送配置



